/// Flutter icons MyFlutterApp
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'MyFlutterApp';

  static const IconData twitter = const IconData(0xf099, fontFamily: _kFontFam);
  static const IconData spinner = const IconData(0xf110, fontFamily: _kFontFam);
  static const IconData instagram = const IconData(0xf16d, fontFamily: _kFontFam);
  static const IconData gittip = const IconData(0xf184, fontFamily: _kFontFam);
  static const IconData binoculars = const IconData(0xf1e5, fontFamily: _kFontFam);
  static const IconData whatsapp = const IconData(0xf232, fontFamily: _kFontFam);
  static const IconData odnoklassniki = const IconData(0xf263, fontFamily: _kFontFam);
  static const IconData facebook_squared = const IconData(0xf308, fontFamily: _kFontFam);
}
